<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Seed the lessons table.
     *
     * @return void
     */
    public function run()
    {
        // Data lessons yang akan dimasukkan ke tabel lessons
        $lessons = [
            ['id_alfabet' => 1, 'text_indo' => 'Anjing', 'text_eng' => 'Dog', 'text_illustration' => 'url_to_illustration_anjing', 'video_sibi' => 'url_to_video_sibi_anjing', 'video_bisindo' => 'url_to_video_bisindo_anjing', 'video_asl' => 'url_to_video_asl_anjing', "image" => "image"],
            ['id_alfabet' => 1, 'text_indo' => 'Apel', 'text_eng' => 'Apple', 'text_illustration' => 'url_to_illustration_apel', 'video_sibi' => 'url_to_video_sibi_apel', 'video_bisindo' => 'url_to_video_bisindo_apel', 'video_asl' => 'url_to_video_asl_apel', "image" => "image"],
            ['id_alfabet' => 2, 'text_indo' => 'Babi', 'text_eng' => 'Pig', 'text_illustration' => 'url_to_illustration_babi', 'video_sibi' => 'url_to_video_sibi_babi', 'video_bisindo' => 'url_to_video_bisindo_babi', 'video_asl' => 'url_to_video_asl_babi', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            ['id_alfabet' => 3, 'text_indo' => 'Cacing', 'text_eng' => 'Worm', 'text_illustration' => 'url_to_illustration_cacing', 'video_sibi' => 'url_to_video_sibi_cacing', 'video_bisindo' => 'url_to_video_bisindo_cacing', 'video_asl' => 'url_to_video_asl_cacing', "image" => "image"],
            // Tambahkan data lessons lainnya di sini
        ];

        // Menyisipkan data ke dalam tabel lessons
        DB::table('lessons')->insert($lessons);
    }
}
